# Generated by Django 3.2.19 on 2023-06-24 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_floors', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('color', models.CharField(choices=[('R', 'Rojo'), ('Az', 'Azul'), ('B', 'Blanco'), ('G', 'Gris')], max_length=100)),
                ('total_floors', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('square_meters', models.FloatField()),
                ('number_rooms', models.PositiveIntegerField()),
                ('number_bathrooms', models.PositiveIntegerField()),
                ('floor', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='exercises2.building')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['-created_at'],
            },
        ),
    ]
