# Generated by Django 3.2.19 on 2023-05-09 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=255)),
                ('design', models.TextField()),
            ],
            options={
                'verbose_name': 'PhoneCase',
                'verbose_name_plural': 'PhoneCases',
            },
        ),
    ]
