# Generated by Django 3.2.19 on 2023-05-23 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('R', 'Rojo'), ('Az', 'Azul'), ('Am', 'Amarillo'), ('N', 'Negro'), ('M', 'Marron'), ('B', 'Blanco'), ('Rs', 'Rosa'), ('V', 'Verde'), ('G', 'Gris'), ('Na', 'Naranja'), ('Mo', 'Morado'), ('P', 'Plateado'), ('D', 'Dorado'), ('T', 'Transparente')], max_length=255)),
                ('phrase', models.CharField(max_length=255)),
                ('design', models.TextField()),
            ],
            options={
                'verbose_name': 'PhoneCase',
                'verbose_name_plural': 'PhoneCases',
                'ordering': ['-created_at'],
            },
        ),
    ]
