# Generated by Django 3.2.19 on 2023-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecase',
            name='color',
            field=models.CharField(choices=[('R', 'Rojo'), ('Az', 'Azul'), ('Am', 'Amarillo'), ('N', 'Negro'), ('M', 'Marron'), ('B', 'Blanco'), ('Rs', 'Rosa'), ('V', 'Verde'), ('G', 'Gris'), ('Na', 'Naranja'), ('Mo', 'Morado'), ('P', 'Plateado'), ('D', 'Dorado'), ('T', 'Transparente')], max_length=50),
        ),
    ]
