# Generated by Django 3.2.19 on 2023-05-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecase',
            options={'ordering': ['-created_at'], 'verbose_name': 'PhoneCase', 'verbose_name_plural': 'PhoneCases'},
        ),
    ]
