# Generated by Django 3.2.19 on 2023-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_case', '0003_alter_phonecase_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecase',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phonecase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
