# Generated by Django 3.2.19 on 2023-06-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_case', '0005_auto_20230614_1901'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_by', to='phone_case.PhoneCase'),
        ),
    ]
