# Generated by Django 3.2.19 on 2023-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_technical_test', '0002_alter_restaurant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
