# Generated by Django 3.2.19 on 2023-09-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity_sept2023', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_workers',
            field=models.ManyToManyField(related_name='workshops', to='new_activity_sept2023.Worker'),
        ),
    ]
