# Generated by Django 3.2.19 on 2023-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity_sept2023', '0003_alter_workshop_workshop_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_workers',
        ),
        migrations.AddField(
            model_name='repair',
            name='workers',
            field=models.ManyToManyField(related_name='repairs', to='new_activity_sept2023.Worker'),
        ),
    ]
