# Generated by Django 3.2.19 on 2023-09-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity_sept2023', '0004_auto_20230919_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
